variables:
  buildConfiguration: 'Release'

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: install

- task: Npm@1
  displayName: 'Build Angular'
  inputs:
    command: custom
    customCommand: run build

- task: Npm@1
  displayName: 'Package Angular'
  inputs:
    command: custom
    customCommand: run package

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'drop'
    targetPath: dist/azure-blob-storage